### ISSUE TITLE
Supporting the new HACS 2.0 platform?

### ISSUE THREAD

**Issue by blue-bean** [p0l0/hagruenbeck_cloud#118]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The new HACS 2.0 comes without support of the sensor platform. Using the Grünbeck integration needs sensor definitions in YAML - so the question is if we could upgrade to HACS 2.0 without using the function?

### Describe the solution you'd like

No need to define sensors in YAML?

### Describe alternatives you've considered

-

### Additional context

-

**Comment by p0l0** [comment]
I have vacation for the next 2 weeks, so I will try to have a look on it.

**Comment by MonsterEnergy-wtf** [comment]
It seems also that somehow the code is not working anymore properly. I can see a lot of errors in the HA logs section related to sensors. I guess this is part of the core problem.

**Comment by MonsterEnergy-wtf** [comment]
Hi @p0l0 ,
I checked out the files from the PR https://github.com/p0l0/hagruenbeck_cloud/pull/134 but I still got many "unknowns". 
![SoftliQSD18](https://github.com/user-attachments/assets/327a9255-447b-4563-85c9-ee4f43e8691a)

Is this intended? As you wanted to merge the code into main, I'm not sure how to test it properly.
Any suggestions?

Best regards,
Martin

**Comment by p0l0** [comment]
> Hi @p0l0 ,
> 
> I checked out the files from the PR https://github.com/p0l0/hagruenbeck_cloud/pull/134 but I still got many "unknowns". 
> 
> Is this intended? As you wanted to merge the code into main, I'm not sure how to test it properly.
> 
> Any suggestions?
> 
> 
> 
> Best regards,
> 
> Martin
> 
> 
> 
> ![SoftliQSD18](https://github.com/user-attachments/assets/327a9255-447b-4563-85c9-ee4f43e8691a)

The latest HACS Release, 1.0.0b1 is already using the changes from PR #134.

I didn't merge it, because I'm still working on the support for SE Series, which has some different response values as SD Series.

Can you please send me the integration diagnostics? With this logs, I will be able to find out why you are not getting values for your sensors.

For me the integration is working without problems for a SD18 Model with HACS 2.0 and Homeassistant 2024.10.4

**Comment by MonsterEnergy-wtf** [comment]
All right.
As I was doing some manual stuff in the configs, I redownloaded 1.0.0b1 again and rebooted HA.

My log shows the following:

Logger: homeassistant
Source: custom_components/gruenbeck_cloud/select.py:73
integration: Grünbeck Cloud ([documentation](https://github.com/p0l0/hagruenbeck_cloud), [issues](https://github.com/p0l0/hagruenbeck_cloud/issues))
First occurred: 14:00:39 (1 occurrences)
Last logged: 14:00:39

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/gruenbeck_cloud/coordinator.py", line 83, in listen
    await self.api.listen(callback=self.async_set_updated_data)
  File "/usr/local/lib/python3.12/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 1048, in listen
    callback(device)
  File "/config/custom_components/gruenbeck_cloud/coordinator.py", line 181, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 145, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gruenbeck_cloud/select.py", line 245, in current_option
    return self.entity_description.value_fn(self.coordinator.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gruenbeck_cloud/select.py", line 73, in <lambda>
    value_fn=lambda device: PARAMETER_OPERATION_MODES[device.parameters.mode],  # type: ignore[index]  # noqa: E501
                            ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 5

**Comment by MonsterEnergy-wtf** [comment]
Finally resolved by removing the whole integration and reinstalled via HACS: Now everything seems to work.
Sorry for the confusion.

I guess this issue can be closed as well.

Ps. Great work. Thanks!
