### ISSUE TITLE
Integration stopped getting data

### ISSUE THREAD

**Issue by MrRagga-** [p0l0/hagruenbeck_cloud#19]
## System Information

version | core-2024.1.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.10.60-qnap
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4272
Installed Version | 1.34.0
Stage | running
Available Repositories | 1382
Downloaded Repositories | 67

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 10
-- | --
resources | 45
views | 28
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 16, 2024 at 5:15 PM
-- | --
current_recorder_run | January 25, 2024 at 11:43 AM
estimated_db_size | 5277.26 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Version: 0.0.2

Even though I am on the latest version it looks similar to https://github.com/p0l0/hagruenbeck_cloud/issues/10

Error:
```
This error originated from a custom integration.

Logger: custom_components.gruenbeck_cloud.coordinator
Source: custom_components/gruenbeck_cloud/coordinator.py:58
Integration: Grünbeck Cloud (documentation, issues)
First occurred: 11:43:57 AM (1 occurrences)
Last logged: 11:43:57 AM

Response status code for https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices/softliQ.D/BS500XXXX/realtime/enter?api-version=2020-08-03 is 500, we expected 202.
```

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/gruenbeck_cloud/coordinator.py:58
Integration: Grünbeck Cloud (documentation, issues)
First occurred: 11:43:57 AM (1 occurrences)
Last logged: 11:43:57 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/gruenbeck_cloud/coordinator.py", line 58, in listen
    await self.api.connect()
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 746, in connect
    await self.enter_sd()
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 559, in enter_sd
    await self._http_request(
  File "/usr/local/lib/python3.11/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 680, in _http_request
    raise PyGruenbeckCloudResponseStatusError(error)
pygruenbeck_cloud.exceptions.PyGruenbeckCloudResponseStatusError: Response status code for https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices/softliQ.D/BS50061383/realtime/enter?api-version=2020-08-03 is 500, we expected 202.
```

Last data retrieved was at 25.1.2024 ~ 2am

### Reproduction steps

1. installed latest version of integration
2. wait until it happens
3. the error message above. appears in the system logs

### Debug logs

```text
enabled debug logging, but no additional logs were shown.
```

**Comment by MrRagga-** [comment]
Turned out, that my WLAN connections was broken and thus the API throws an internal server error. Information/error like "no data retrieved since XXXX" would be much better. Or providing a local API would detect it. But not a problem of this integration.
Sorry for the noise!
