### ISSUE TITLE
Problem mit dem Datum aus API

### ISSUE THREAD

**Issue by tropifruit** [p0l0/hagruenbeck_cloud#91]
### System Health details

Hi, bei mir klappt alles wie beschrieben, ich kann alles importieren. Melde mich dann an und bekomme folgende Meldung: 

softliQ.D/BS50046307
Keine Geräte oder Entitäten
Einrichtung fehlgeschlagen, wird erneut versucht: Unable to get data from API: time data '2024-03-23T13:46:45' does not match format '%Y-%m-%dT%H:%M:%S.%f'

Kannst du mir sagen, was ich tun kann, um das Problem zu beheben?

Danke dir. 

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi, bei mir klappt alles wie beschrieben, ich kann alles importieren. Melde mich dann an und bekomme folgende Meldung: 

softliQ.D/BS50046307
Keine Geräte oder Entitäten
Einrichtung fehlgeschlagen, wird erneut versucht: Unable to get data from API: time data '2024-03-23T13:46:45' does not match format '%Y-%m-%dT%H:%M:%S.%f'

Kannst du mir sagen, was ich tun kann, um das Problem zu beheben?

Danke dir. 

### Reproduction steps

1.
2.
3.
...
siehe oben

### Debug logs

```text
2024-06-29 20:55:01.394 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hochwasserportal which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.395 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.397 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dwd_pollenflug which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.398 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration landroid_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.399 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.401 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dwd_weather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.402 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dwd which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.404 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration roborock which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.405 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gruenbeck_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:01.407 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-29 20:55:04.905 ERROR (MainThread) [homeassistant.components.sensor] The hochwasserportal platform for the sensor integration does not support platform setup. Please remove it from your config.
2024-06-29 20:55:08.299 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-29 20:55:11.469 INFO (SyncWorker_10) [fritzconnection] Unable to retrieve resource 'http://192.168.178.51:49000/igddesc.xml' from the device.
2024-06-29 20:55:11.476 INFO (SyncWorker_9) [fritzconnection] Unable to retrieve resource 'http://192.168.178.67:49000/igddesc.xml' from the device.
2024-06-29 20:55:11.483 INFO (SyncWorker_1) [fritzconnection] Unable to retrieve resource 'http://192.168.178.57:49000/igddesc.xml' from the device.
2024-06-29 20:55:11.492 INFO (SyncWorker_5) [fritzconnection] Unable to retrieve resource 'http://192.168.178.21:49000/igddesc.xml' from the device.
2024-06-29 20:55:11.506 INFO (SyncWorker_8) [fritzconnection] Unable to retrieve resource 'http://192.168.178.24:49000/igddesc.xml' from the device.
2024-06-29 20:55:28.891 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set date_str = states('sensor.gruenbeck_original_date') %} {% if date_str %}
  {% set parsed_date = strptime(date_str, '%Y-%m-%dT%H:%M:%S') %}
  {{ parsed_date }}
{% else %}
  unknown
{% endif %}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2100, in strptime
    return datetime.strptime(string, fmt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'unknown' does not match format '%Y-%m-%dT%H:%M:%S'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 603, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2616, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 2, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2103, in strptime
    raise_no_default("strptime", string)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1853, in raise_no_default
    raise ValueError(
ValueError: Template error: strptime got invalid input 'unknown' when rendering template '{% set date_str = states('sensor.gruenbeck_original_date') %} {% if date_str %}
  {% set parsed_date = strptime(date_str, '%Y-%m-%dT%H:%M:%S') %}
  {{ parsed_date }}
{% else %}
  unknown
{% endif %}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 715, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 605, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: strptime got invalid input 'unknown' when rendering template '{% set date_str = states('sensor.gruenbeck_original_date') %} {% if date_str %}
  {% set parsed_date = strptime(date_str, '%Y-%m-%dT%H:%M:%S') %}
  {{ parsed_date }}
{% else %}
  unknown
{% endif %}' but no default was specified
2024-06-29 20:55:28.907 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: strptime got invalid input 'unknown' when rendering template '{% set date_str = states('sensor.gruenbeck_original_date') %} {% if date_str %}
  {% set parsed_date = strptime(date_str, '%Y-%m-%dT%H:%M:%S') %}
  {{ parsed_date }}
{% else %}
  unknown
{% endif %}' but no default was specified') while processing template 'Template<template=({% set date_str = states('sensor.gruenbeck_original_date') %} {% if date_str %}
  {% set parsed_date = strptime(date_str, '%Y-%m-%dT%H:%M:%S') %}
  {{ parsed_date }}
{% else %}
  unknown
{% endif %}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.gruenbeck_date_parsed'
2024-06-29 20:55:28.923 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
```

**Comment by dv3131** [comment]
Ich habe leider genau das gleiche Problem bei meiner Installation (SoftliQ SD21).
Gibt es dazu schon irgendeinen Lösungsansatz?

**Comment by emaa10** [comment]
Gleiches Problem hier.

**Comment by ricomahro1** [comment]
Ich habe auch noch den gleichen Fehler. Kann sich bitte jemand dem Fehler widmen?

**Comment by ricomahro1** [comment]
Bei mir ist der Fehler anscheinend ein anderer. ich kann im Debuglog sehen, dass die Daten erfolgreich übermittelt werden, ich jedoch diese Fehlermeldung von einem Wasseraustritt mal hatte und der Zeitstempel anscheinen zu kurz ist
{'isResolved': True, 'date': '2024-04-23T06:34:20', 'message': 'Wasseraustritt am Aufstellort softliQ!', 'type': 'error'}
Sonstige Zeitstempel sehen so aus: 'date': '2024-04-17T01:52:57.87'

Genau das Datum wird bei mir auch in der HA Oberfläche als Fehler angezeigt 2024-04-23T06:34:20

**Comment by Net-Felix** [comment]
> Nachdem ich den Fehlerspeicher am Gerät gelöscht habe, den Grünbeck Cloud Account gelöscht habe und diesen nochmal erstellt habe, ging die Einrichtung erfolgreich. (Achtung: das Gerät im vorhandenen Cloudaccount löschen und neu verbinden reicht nicht aus, damit die Meldungen wirklich gelöscht sind)

Und wenn dann ein Fehler auftritt klappt das wieder nicht oder funktioniert das dann weiter?
ggf kannst du das mal testen indem du einen Wasseraustritt simulierst

**Comment by Net-Felix** [comment]
hab einen fix für das modul gefunden: https://github.com/p0l0/pygruenbeck_cloud/issues/199
ggf kann das der entwickler reinpatchen

**Comment by bernd780** [comment]
Heute installiert, und genau der gleiche Fehler. Bitti bitti patchen 👍

**Comment by lenzsi** [comment]
Hi,
gleicher fehler.
https://github.com/p0l0/pygruenbeck_cloud/issues/199
angepasst im models.py, immernoch gleicher fehler.
tzinfo=datetime.UTC auf tzinfo=datetime.MEZ angepasst, auch keine besserung
gerät auf englisch gestellt, auch keine besserung

**Comment by lenzsi** [comment]
Freunde, ich habs gelöst!

🛠 Fix: Unable to get data from API: time data '' does not match format
Problem
Die Grünbeck-Cloud liefert für bestimmte Felder (z. B. Inbetriebnahme-Datum, Fehlerprotokolle oder Verbrauchsdaten) gelegentlich leere Strings (''). Die zugrunde liegende Bibliothek pygruenbeck_cloud nutzt strptime zur Umwandlung, was bei leeren Strings zum Absturz der gesamten Integration führt.

Lösung (Manueller Patch)
Man muss die decoder-Funktionen in der Datei models.py so anpassen, dass sie leere Werte abfangen (None if not value else ...).

Pfad zur Datei (im Home Assistant Core Container): /usr/local/lib/python3.13/site-packages/pygruenbeck_cloud/models.py (Hinweis: Die Python-Version im Pfad kann je nach HA-Version variieren, z.B. 3.12 oder 3.13)

So siehst du die Problemzeilen
grep -n "strptime" models.py

k3s01-lenzsi:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud# grep -n "strptime" models.py
58:            decoder=lambda value: datetime.datetime.strptime(
74:            #decoder=lambda value: datetime.datetime.strptime(value, "%Y-%m-%d").date(),
75:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
234:                datetime.datetime.strptime(value, "%H:%M").time()
252:                datetime.datetime.strptime(value, "%H:%M").time()
270:                datetime.datetime.strptime(value, "%H:%M").time()
288:                datetime.datetime.strptime(value, "%H:%M").time()
306:                datetime.datetime.strptime(value, "%H:%M").time()
324:                datetime.datetime.strptime(value, "%H:%M").time()
342:                datetime.datetime.strptime(value, "%H:%M").time()
360:                datetime.datetime.strptime(value, "%H:%M").time()
378:                datetime.datetime.strptime(value, "%H:%M").time()
396:                datetime.datetime.strptime(value, "%H:%M").time()
414:                datetime.datetime.strptime(value, "%H:%M").time()
432:                datetime.datetime.strptime(value, "%H:%M").time()
450:                datetime.datetime.strptime(value, "%H:%M").time()
468:                datetime.datetime.strptime(value, "%H:%M").time()
486:                datetime.datetime.strptime(value, "%H:%M").time()
507:                datetime.datetime.strptime(value, "%H:%M").time()
525:                datetime.datetime.strptime(value, "%H:%M").time()
543:                datetime.datetime.strptime(value, "%H:%M").time()
561:                datetime.datetime.strptime(value, "%H:%M").time()
579:                datetime.datetime.strptime(value, "%H:%M").time()
597:                datetime.datetime.strptime(value, "%H:%M").time()
1111:            decoder=lambda value: datetime.datetime.strptime(
1123:            decoder=lambda value: datetime.datetime.strptime(
1137:            #decoder=lambda value: datetime.datetime.strptime(value, "%Y-%m-%d").date(),
1138:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y.%m.%d").date(),
1149:            #decoder=lambda value: datetime.datetime.strptime(value, "%Y.%m.%d").date(),
1150:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y.%m.%d").date(),
1201:            decoder=lambda value: datetime.datetime.strptime(value, "%z").tzinfo,
1211:            #decoder=lambda value: datetime.datetime.strptime(value, "%Y-%m-%d").date(),
1212:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y.%m.%d").date(),


Gehe zu Zeile 1147. (In vi kannst du :1147 eingeben und Enter drücken).
Ändere die Zeile von: Python  decoder=lambda value: datetime.datetime.strptime(value, "%Y.%m.%d").date(),
in: Python  decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y.%m.%d").date(),

zusätzlich habe ich das in den zeilen gemacht

* Zeile 74: decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
* Zeile 1136: decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
* Zeile 1208: decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),

FINAL soll es so aussehen:

k3s01-lenzsi:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud# grep -n "strptime" models.py
58:            decoder=lambda value: datetime.datetime.strptime(
74:            #decoder=lambda value: datetime.datetime.strptime(value, "%Y-%m-%d").date(),
75:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
234:                datetime.datetime.strptime(value, "%H:%M").time()
252:                datetime.datetime.strptime(value, "%H:%M").time()
270:                datetime.datetime.strptime(value, "%H:%M").time()
288:                datetime.datetime.strptime(value, "%H:%M").time()
306:                datetime.datetime.strptime(value, "%H:%M").time()
324:                datetime.datetime.strptime(value, "%H:%M").time()
342:                datetime.datetime.strptime(value, "%H:%M").time()
360:                datetime.datetime.strptime(value, "%H:%M").time()
378:                datetime.datetime.strptime(value, "%H:%M").time()
396:                datetime.datetime.strptime(value, "%H:%M").time()
414:                datetime.datetime.strptime(value, "%H:%M").time()
432:                datetime.datetime.strptime(value, "%H:%M").time()
450:                datetime.datetime.strptime(value, "%H:%M").time()
468:                datetime.datetime.strptime(value, "%H:%M").time()
486:                datetime.datetime.strptime(value, "%H:%M").time()
507:                datetime.datetime.strptime(value, "%H:%M").time()
525:                datetime.datetime.strptime(value, "%H:%M").time()
543:                datetime.datetime.strptime(value, "%H:%M").time()
561:                datetime.datetime.strptime(value, "%H:%M").time()
579:                datetime.datetime.strptime(value, "%H:%M").time()
597:                datetime.datetime.strptime(value, "%H:%M").time()
1111:            decoder=lambda value: datetime.datetime.strptime(
1123:            decoder=lambda value: datetime.datetime.strptime(
1137:            #decoder=lambda value: datetime.datetime.strptime(value, "%Y-%m-%d").date(),
1138:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
1149:            #decoder=lambda value: datetime.datetime.strptime(value, "%Y.%m.%d").date(),
1150:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y.%m.%d").date(),
1201:            decoder=lambda value: datetime.datetime.strptime(value, "%z").tzinfo,
1211:            #decoder=lambda value: datetime.datetime.strptime(value, "%Y-%m-%d").date(),
1212:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
k3s01-lenzsi:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud#  



⚠️ Wichtiger Hinweis: Nicht persistent!
Diese Änderung wird direkt im Dateisystem des Containers vorgenommen. Das bedeutet:

Bei einem Home Assistant Update oder einem Neuaufbau des Containers geht dieser Patch verloren!

Man sollte sich eine Kopie der editierten models.py nach /config/models.py.bak speichern, um sie nach einem Update schnell wieder zurückkopieren zu können.

Zusammenfassung der Aktion:
1. Datei patchen wie oben beschrieben.

2. Mit :wq! (in vi) speichern.

3. Home Assistant Neustart durchführen.

Damit sollte die Integration wieder funktionieren.

Viele Grüße

**Comment by zillion42** [comment]
Hello,

This almost worked for me too. In the container
`docker exec -it homeassistant bash`
If you are using Advanced SSH & Web Terminal
under
`cd /usr/local/lib/python3.13/site-packages/pygruenbeck_cloud/`

I edited the corresponding lines (74, 1136, 1147, 1208) as @lenzsi suggested:

```
homeassistant:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud# grep -n "strptime" models.py
58:            decoder=lambda value: datetime.datetime.strptime(
74:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
233:                datetime.datetime.strptime(value, "%H:%M").time()
251:                datetime.datetime.strptime(value, "%H:%M").time()
269:                datetime.datetime.strptime(value, "%H:%M").time()
287:                datetime.datetime.strptime(value, "%H:%M").time()
305:                datetime.datetime.strptime(value, "%H:%M").time()
323:                datetime.datetime.strptime(value, "%H:%M").time()
341:                datetime.datetime.strptime(value, "%H:%M").time()
359:                datetime.datetime.strptime(value, "%H:%M").time()
377:                datetime.datetime.strptime(value, "%H:%M").time()
395:                datetime.datetime.strptime(value, "%H:%M").time()
413:                datetime.datetime.strptime(value, "%H:%M").time()
431:                datetime.datetime.strptime(value, "%H:%M").time()
449:                datetime.datetime.strptime(value, "%H:%M").time()
467:                datetime.datetime.strptime(value, "%H:%M").time()
485:                datetime.datetime.strptime(value, "%H:%M").time()
506:                datetime.datetime.strptime(value, "%H:%M").time()
524:                datetime.datetime.strptime(value, "%H:%M").time()
542:                datetime.datetime.strptime(value, "%H:%M").time()
560:                datetime.datetime.strptime(value, "%H:%M").time()
578:                datetime.datetime.strptime(value, "%H:%M").time()
596:                datetime.datetime.strptime(value, "%H:%M").time()
1110:            decoder=lambda value: datetime.datetime.strptime(
1122:            decoder=lambda value: datetime.datetime.strptime(
1136:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
1147:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y.%m.%d").date(),
1198:            decoder=lambda value: datetime.datetime.strptime(value, "%z").tzinfo,
1208:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),

```

Additionally, I edited

```
homeassistant:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud# grep -n "%f" models.py
56: encoder=lambda value: value.strftime("%Y-%m-%dT%H:%M:%S.%f"),
59: value, "%Y-%m-%dT%H:%M:%S.%f"
```

change line 59 from:

`value, "%Y-%m-%dT%H:%M:%S.%f"`
to
`value.split('.')[0], "%Y-%m-%dT%H:%M:%S"`

Then create a backup:

`homeassistant:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud# cp models.py /config/models.py.bak`

`exit`
Restart and it works again!

Since /config/ persists, you can simply restore the patch after a Home Assistant update:
`docker exec -it homeassistant cp /config/models.py.bak /usr/local/lib/python3.13/site-packages/pygruenbeck_cloud/models.py`

Thanks @lenzsi

------------------------


Hallo,

das hat bei mir auch, fast funktioniert. Im container
`docker exec -it homeassistant bash`
Wenn man Advanced SSH & Web Terminal benutzt
unter
`cd /usr/local/lib/python3.13/site-packages/pygruenbeck_cloud/`

habe ich die entsprechenden Zeilen (74, 1136, 1147, 1208) wie von @lenzsi beschrieben bearbeitet:

```
homeassistant:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud# grep -n "strptime" models.py
58:            decoder=lambda value: datetime.datetime.strptime(
74:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
233:                datetime.datetime.strptime(value, "%H:%M").time()
251:                datetime.datetime.strptime(value, "%H:%M").time()
269:                datetime.datetime.strptime(value, "%H:%M").time()
287:                datetime.datetime.strptime(value, "%H:%M").time()
305:                datetime.datetime.strptime(value, "%H:%M").time()
323:                datetime.datetime.strptime(value, "%H:%M").time()
341:                datetime.datetime.strptime(value, "%H:%M").time()
359:                datetime.datetime.strptime(value, "%H:%M").time()
377:                datetime.datetime.strptime(value, "%H:%M").time()
395:                datetime.datetime.strptime(value, "%H:%M").time()
413:                datetime.datetime.strptime(value, "%H:%M").time()
431:                datetime.datetime.strptime(value, "%H:%M").time()
449:                datetime.datetime.strptime(value, "%H:%M").time()
467:                datetime.datetime.strptime(value, "%H:%M").time()
485:                datetime.datetime.strptime(value, "%H:%M").time()
506:                datetime.datetime.strptime(value, "%H:%M").time()
524:                datetime.datetime.strptime(value, "%H:%M").time()
542:                datetime.datetime.strptime(value, "%H:%M").time()
560:                datetime.datetime.strptime(value, "%H:%M").time()
578:                datetime.datetime.strptime(value, "%H:%M").time()
596:                datetime.datetime.strptime(value, "%H:%M").time()
1110:            decoder=lambda value: datetime.datetime.strptime(
1122:            decoder=lambda value: datetime.datetime.strptime(
1136:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),
1147:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y.%m.%d").date(),
1198:            decoder=lambda value: datetime.datetime.strptime(value, "%z").tzinfo,
1208:            decoder=lambda value: None if not value else datetime.datetime.strptime(value, "%Y-%m-%d").date(),

```

Zusätzlich aber noch:

```
homeassistant:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud# grep -n "%f" models.py
56:            encoder=lambda value: value.strftime("%Y-%m-%dT%H:%M:%S.%f"),
59:                value, "%Y-%m-%dT%H:%M:%S.%f"
```

in Zeile 59 ändern von:
`value, "%Y-%m-%dT%H:%M:%S.%f"`
in
`value.split('.')[0], "%Y-%m-%dT%H:%M:%S"`

dann noch Backup erstellen:
`homeassistant:/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud# cp models.py /config/models.py.bak`
`exit`
Neustarten und es geht wieder !

Da /config/ erhalten bleibt, kann man nach einem Home Assistant Update den Patch einfach zurückspielen:
`docker exec -it homeassistant cp /config/models.py.bak /usr/local/lib/python3.13/site-packages/pygruenbeck_cloud/models.py`

Danke @lenzsi
